# Generated by Django 5.0.6 on 2024-05-22 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_privatechat_chats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='chats',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='users',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='private_chats_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='private_chats_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
