# Generated by Django 5.0.6 on 2024-05-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_privatechat_chats_remove_privatechat_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='chats',
            field=models.ManyToManyField(related_name='private_chats', to='chat.chat'),
        ),
    ]
